### ISSUE TITLE
Issue with Target Framwork

### ISSUE THREAD

**Issue by brutalbryan** [sitefinitysteve/RandomSiteControlsMVC#5]
Hey Steve,

I am trying to install your NuGet package to my version of Sitefinity (10.1) however when the NuGet is installed the following error is occurred: 

> Severity | Code | Description | Project | File | Line | Suppression State
> -- | -- | -- | -- | -- | -- | --
> Error |   | Could not install package 'RandomSiteControlsMVC 10.1.6500.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. |   |   | 0 |  
> 

I then changed my target framework to 4.5.2 and it was able to install except after I cleaned and built the project, this issue occurred:

> Could not load type 'SfWebApp.MVC.Models.TabStrip.TabStripModel' from assembly 'SfWebApp, Version=10.1.6500.0, Culture=neutral, PublicKeyToken=null'.

**Comment by sitefinitysteve** [comment]
Huh, "SfWebApp.MVC.Models.TabStrip.TabStripModel" isn't mine, but you could easily get around it by just making a dummy class thrown somewhere that resolves that object.

Looks like something in your webapp project, no?  Have you tried a solution search for TabStripModel?

On the versioning, yeah so 4.5.2 is the requirement, sorry about that one :)

v11 SF will be targeting 4.7 just an FYI so I'll be moving to that as well with them.

**Comment by brutalbryan** [comment]
Thanks Steve!
